version: "3.8"

services:
  db:
    image: postgres:14.1
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - transcendence-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "4210:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - transcendence-pgadmin-data:/var/lib/pgadmin

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    ports:
      - 9090:9000
    env_file:
      - .env
    entrypoint: sh
    command: -c "mkdir -p /data/.minio.sys/buckets &&
      cp -r /policies/* /data/.minio.sys/ &&
      cp -r /export/* /data/ &&
      /usr/bin/minio server /data"
    volumes:
      - "transcendence-minio-data:/export/static"
      - "./minio/policy:/policies/buckets/static"

  api:
    build:
      context: api
    ports:
      - "4211:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - "./api:/app:delegated"
      - /app/node_modules
    working_dir: /app
    command: |
      bash -c
      "yarn migration:run &&
      PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER $POSTGRES_DB -f db/init.sql &&
      yarn start:dev"

  front:
    build:
      context: front
    ports:
      - "4212:3000"
    env_file:
      - .env
    volumes:
      - "./front:/app:delegated"
      - /app/node_modules
    working_dir: /app
    command: "yarn start"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "4213:8080"
    volumes:
      - "./docs/openapi.yaml:/openapi.yaml"
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  transcendence-db-data:
  transcendence-pgadmin-data:
  transcendence-minio-data:
