version: '3.8'

services:
  db:
    image: postgres:14.1
    ports:
      - '15432:5432'
    env_file:
      - .env
    volumes:
      - transcendence-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '4210:80'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - transcendence-pgadmin-data:/var/lib/pgadmin

  api:
    build:
      context: api
    ports:
      - '4211:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - './api:/app:delegated'
      - /app/node_modules
    working_dir: /app
    command: 'yarn migration:run && yarn start:dev'

  front:
    build:
      context: front
    ports:
      - '4212:3000'
    env_file:
      - .env
    volumes:
      - './front:/app:delegated'
      - /app/node_modules
    working_dir: /app
    command: 'yarn start'

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '4213:8080'
    volumes:
      - './docs/openapi.yaml:/openapi.yaml'
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  transcendence-db-data:
    driver: local
  transcendence-pgadmin-data:
    driver: local
